### ISSUE TITLE
Typescript & Javascript prompt for cycle-scripts

### ISSUE THREAD

**Issue by nickbalestra** [cyclejs-community/create-cycle-app#108]
This issue to discuss if, when, and how, to bring TS and JS together within CCA & cycle-scripts.

Issues that emerged from this:

- https://github.com/cyclejs-community/create-cycle-app/issues/107
- https://github.com/cyclejs-community/create-cycle-app/issues/103
- https://github.com/cyclejs-community/create-cycle-app/issues/101

**Comment by jvanbruegge** [comment]
I think the way it is in #105 is quite good. I don't see big tradeoffs. We use native ES6 templates that allow us to reduce code doublication and therefore a source of possible mistakes. Webpack blocks makes this aproach feasable.
I would however move from the custom build/start scripts to just spawing the webpack cli, as this allows us to completely remove traces of the flavor on eject and not litter the working directory with scripts.
I think the init question should be part of the flavor, not part of CCA, because they are only used by the flavor.

**Comment by jvanbruegge** [comment]
Done in V4
