### ISSUE TITLE
ES6 + Webkit flavour doesn;t have "eject"

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app#55]
rather it has remove-training-wheels

**Comment by nickbalestra** [comment]
Thanks @SteveALee for reporting this, it seems that something is off with the publishing of the latest releases. 
@geovanisouza92 Anything to consider before I go ahead and manually publish all the latest releases? Perhaps is time to deep dive on #52 or #44 ?

**Comment by geovanisouza92** [comment]
Nope, you can move on :smiley:

**Comment by nickbalestra** [comment]
@SteveALee if you want you can give the next version a go:

```
npm i -g create-cycle-app@next
```

the eject issue should be fixed there

**Comment by nickbalestra** [comment]
fixed with #63

**Comment by SteveALee** [comment]
@nickbalestra Sorry for being late to test this. I was just going to git it a spin but can't see from the readme how to list and select the flavors, I know I did it before

**Comment by nickbalestra** [comment]
there is only one core flavor from now on. This willl allow us to focus on it and provide a great experience instead of having multiple very basics setup. Also cause cycle [unified](https://github.com/cyclejs/cyclejs/issues/425) is coming, no more need to choose streamLib.
Custom flavors are still possible and can be installed using the `--flavor` flag.

**Comment by SteveALee** [comment]
Ah, OK so I confirm the problem has gone away as the flavour has vanished :)

IS good to hear unified is coming. Though I do like the small code size / complexity of the original version

**Comment by nickbalestra** [comment]
Thank you @SteveALee for double checking!
