### ISSUE TITLE
A few questions on project development

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app#56]
This is a great tool! Keeping config out of sight is great for beginners. But like all 'magic' I worry about it as I'm likely to have to understand/maintain it at some point. Mind you magic is a lot less of a problem with build tools than live code (I chose cyclejs over the excellent MobX as I felt that had a bit too much magic, I might review that - heh). 

So a few questions came up as someone new to this and wanting to try it out on a new project, partly for my own interest and partly to support our great community.

1. Does the hidden config ever change? Do you update dependency versions for us? If so when? When we update this project only? That seems to be the case as I see no live updating.

2. Are there any advantages to keeping the training wheels on for production project with expected long lifetime? Or is it best to eject and treat as a starter boilerplate The current examples simply create a couple of config files which is not at all complex to manage and being able to shrink wrap dependencies etc is important for public code

3. How do we add new features such as linting or css loaders to our projects? (reminds me a template CSS file might be a good addition to the flavours). The obvious answer is we simply edit the scripts to alter the configs. But is there more we need to do?

If it makes sense to keep the wheels on for a production project then we'd need a list of the changes per release.

I hope this is helpful

**Comment by nickbalestra** [comment]
hehe you very welcome!

1. Yes it could (only for the core-flavors). How offten it will depends, we have no rules in this regard yet. For custom flavors this is will be done by the owner/maintainers.

2. It depends, if you don't need much changes from what the core-flavors offer you, then is just fine not to eject, especially cause this could result in 'free' updates coming down for you (^ point 1). You could decide to use it as a boilerplate starter if that is what you looking for, that's also super fine, and you could even create your own flavor and maintain that so that once you update it all your app relying on it could take advantage of that (again, ^ point 1 ). 

3. We don't handle that within core flavor yet, and agree that adding some CSS support will be a good idea, can you open a separate issue for this point so that we can bring the discussion on how we might wan to implement this in a separate thread?

Having said that, I will say that in general core-flavor aim to be very simple, with the goal to allow to mix and match different stream libraries, and language/bundlers for the main purpose of easing people to getting started with cycle.js, everything more complex or specific should probably be better developed as a custom flavor. 

Hope this answer your question

**Comment by SteveALee** [comment]
yes they helped thanks

I'll make a minor PR to readme

I agree the main use case should be easy bootstrap. But also imagining a more advanced workflow like this:

  Use existing flavour -> [opt eject] -> modify config or flavour -> create custom flavour -> publish

And was trying to figure how that might work.

**Comment by geovanisouza92** [comment]
I would really like to see something like this "create flavor from project"

Em qua, 4 de jan de 2017 08:06, Steve Lee <notifications@github.com>
escreveu:

**Comment by nickbalestra** [comment]
@geovanisouza92 @SteveALee I think this issue: https://github.com/cyclejs-community/create-cycle-app/issues/27 could be somehow related. I like the idea too. Let's bring the conversation there
